# Generated by Django 5.2.6 on 2025-09-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('caption_style', models.CharField(blank=True, max_length=100, null=True)),
                ('translated_caption', models.TextField(blank=True, null=True)),
                ('target_platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
