# Generated by Django 5.2.6 on 2025-10-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Image Upload', 'verbose_name_plural': 'Image Uploads'},
        ),
        migrations.AddField(
            model_name='imageupload',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
