# Generated by Django 4.2.18 on 2025-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imageupload_options_imageupload_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='original_caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
